// Product database
export const productDatabase = [
  {
    id: "1",
    name: "Premium Headphones",
    price: 2499.99,
    image: "/images/whey.jpeg", // Updated path
    category: "featured",
    description:
      "Experience crystal-clear sound with our Premium Headphones. Featuring active noise cancellation, comfortable ear cups, and a long-lasting battery, these headphones are perfect for music lovers and professionals alike.",
    features: [
      "Active Noise Cancellation",
      "40-hour battery life",
      "Bluetooth 5.0 connectivity",
      "Built-in microphone for calls",
      "Foldable design for easy storage",
    ],
    specifications: {
      "Driver Size": "40mm",
      "Frequency Response": "20Hz - 20kHz",
      Impedance: "32 Ohms",
      Weight: "250g",
      Charging: "USB-C",
      Battery: "700mAh",
    },
    stock: 15,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Wireless Earbuds",
    price: 1799.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "featured",
    description:
      "Enjoy your music on the go with our Wireless Earbuds. These compact earbuds deliver powerful sound, feature touch controls, and come with a charging case that provides up to 24 hours of total playtime.",
    features: [
      "Touch controls",
      "Water-resistant (IPX5)",
      "6-hour playtime per charge",
      "24-hour total playtime with case",
      "Noise isolation",
    ],
    specifications: {
      "Driver Size": "8mm",
      "Frequency Response": "20Hz - 20kHz",
      "Bluetooth Version": "5.2",
      "Battery Capacity": "50mAh (earbuds), 500mAh (case)",
      Charging: "USB-C",
      Weight: "5g per earbud, 45g case",
    },
    stock: 23,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "3",
    name: "Smart Watch",
    price: 3899.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "featured",
    description:
      "Stay connected and track your fitness with our Smart Watch. This versatile device monitors your heart rate, counts steps, displays notifications, and has a battery life of up to 7 days.",
    features: [
      "Heart rate monitoring",
      "Step counter and activity tracking",
      "Sleep analysis",
      "Notification display",
      "Water-resistant (50m)",
      "7-day battery life",
    ],
    specifications: {
      Display: '1.4" AMOLED',
      Resolution: "454 x 454 pixels",
      Sensors: "Heart rate, Accelerometer, Gyroscope",
      Battery: "420mAh",
      Connectivity: "Bluetooth 5.0, GPS",
      Compatibility: "iOS 10.0+, Android 6.0+",
    },
    stock: 8,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "4",
    name: "Bluetooth Speaker",
    price: 1599.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "featured",
    description:
      "Fill your space with rich, immersive sound using our Bluetooth Speaker. With 360° sound projection, waterproof design, and 12 hours of playtime, it's perfect for any occasion, indoors or outdoors.",
    features: [
      "360° sound projection",
      "Waterproof (IPX7)",
      "12-hour playtime",
      "Built-in microphone for calls",
      "Connects to multiple devices",
    ],
    specifications: {
      "Output Power": "20W",
      "Frequency Response": "60Hz - 20kHz",
      Battery: "3600mAh",
      "Charging Time": "3 hours",
      "Bluetooth Range": "30 feet",
      Weight: "560g",
    },
    stock: 19,
    rating: 4.5,
    reviews: 78,
  },
  {
    id: "5",
    name: "Fitness Tracker",
    price: 1199.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "featured",
    description:
      "Monitor your health and fitness goals with our Fitness Tracker. Track steps, heart rate, sleep quality, and more. The slim design and long battery life make it perfect for everyday wear.",
    features: [
      "Step counting",
      "Heart rate monitoring",
      "Sleep tracking",
      "Multiple sport modes",
      "Notification alerts",
      "10-day battery life",
    ],
    specifications: {
      Display: '0.96" OLED',
      Battery: "110mAh",
      "Water Resistance": "IP68",
      Sensors: "Heart rate, Accelerometer",
      Connectivity: "Bluetooth 4.2",
      Weight: "24g",
    },
    stock: 27,
    rating: 4.4,
    reviews: 112,
  },
  // Electronics
  {
    id: "6",
    name: "Smartphone",
    price: 13999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "electronics",
    description:
      "Experience cutting-edge technology with our Smartphone. Featuring a stunning display, powerful processor, and advanced camera system, this phone delivers exceptional performance for all your needs.",
    features: [
      '6.5" AMOLED display',
      "Triple camera system",
      "8GB RAM, 256GB storage",
      "5G connectivity",
      "Fast charging",
      "Water and dust resistant",
    ],
    specifications: {
      Processor: "Octa-core 2.8GHz",
      Display: '6.5" AMOLED, 120Hz',
      Camera: "48MP main, 12MP ultra-wide, 8MP telephoto",
      Battery: "4500mAh",
      OS: "Android 12",
      Dimensions: "158 x 73 x 8.1mm",
    },
    stock: 12,
    rating: 4.7,
    reviews: 203,
  },
  {
    id: "7",
    name: "Tablet",
    price: 6999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "electronics",
    description:
      "Enhance your productivity and entertainment with our Tablet. The large, high-resolution display is perfect for work, gaming, and streaming, while the powerful processor ensures smooth performance.",
    features: [
      '10.9" Liquid Retina display',
      "64GB/256GB storage options",
      "12MP wide camera",
      "Stereo speakers",
      "All-day battery life",
      "Compatible with keyboard and stylus",
    ],
    specifications: {
      Processor: "A14 Bionic chip",
      Display: '10.9" Liquid Retina, 2360 x 1640',
      Camera: "12MP wide, 7MP front",
      Battery: "28.6Wh",
      Connectivity: "Wi-Fi 6, Bluetooth 5.0",
      Dimensions: "247.6 x 178.5 x 6.1mm",
    },
    stock: 16,
    rating: 4.8,
    reviews: 145,
  },
  {
    id: "8",
    name: "Laptop",
    price: 19999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "electronics",
    description:
      "Power through your workday with our high-performance Laptop. With a fast processor, ample storage, and long battery life, this laptop is designed for professionals, students, and creatives alike.",
    features: [
      '15.6" Full HD display',
      "Intel Core i7 processor",
      "16GB RAM, 512GB SSD",
      "Backlit keyboard",
      "10-hour battery life",
      "Windows 11 Pro",
    ],
    specifications: {
      Processor: "Intel Core i7-1165G7",
      Graphics: "Intel Iris Xe",
      Memory: "16GB DDR4",
      Storage: "512GB NVMe SSD",
      Display: '15.6" Full HD (1920 x 1080)',
      Ports: "2x USB-C, 2x USB-A, HDMI, 3.5mm audio",
    },
    stock: 7,
    rating: 4.9,
    reviews: 178,
  },
  {
    id: "9",
    name: "Digital Camera",
    price: 8999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "electronics",
    description:
      "Capture life's moments with stunning clarity using our Digital Camera. With advanced features and intuitive controls, this camera is perfect for both beginners and experienced photographers.",
    features: [
      "24.2MP CMOS sensor",
      "4K video recording",
      '3" vari-angle touchscreen',
      "Built-in Wi-Fi and Bluetooth",
      "45-point autofocus system",
      "ISO range of 100-25600",
    ],
    specifications: {
      Sensor: "24.2MP APS-C CMOS",
      Processor: "DIGIC 8",
      Autofocus: "45-point all cross-type",
      Video: "4K at 24p, Full HD at 60p",
      Battery: "LP-E17, approx. 600 shots",
      Weight: "485g (body only)",
    },
    stock: 9,
    rating: 4.6,
    reviews: 92,
  },
  {
    id: "10",
    name: "Power Bank",
    price: 799.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "electronics",
    description:
      "Stay charged on the go with our high-capacity Power Bank. With fast charging capabilities and multiple ports, it can charge multiple devices simultaneously, making it perfect for travel and daily use.",
    features: [
      "20,000mAh capacity",
      "Fast charging (18W)",
      "Dual USB-A ports",
      "USB-C input/output",
      "LED power indicator",
      "Compact and portable design",
    ],
    specifications: {
      Capacity: "20,000mAh",
      Input: "USB-C (5V/3A), Micro USB (5V/2A)",
      Output: "USB-A (5V/3A, 9V/2A, 12V/1.5A), USB-C (5V/3A, 9V/2A, 12V/1.5A)",
      Dimensions: "150 x 70 x 15mm",
      Weight: "340g",
      "Recharge Time": "4-5 hours (with 18W charger)",
    },
    stock: 31,
    rating: 4.5,
    reviews: 217,
  },
  // Home & Living
  {
    id: "11",
    name: "Smart Light Bulbs",
    price: 599.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "home",
    description:
      "Transform your home lighting with our Smart Light Bulbs. Control brightness, color, and schedules from your smartphone or voice assistant for the perfect ambiance in any room.",
    features: [
      "16 million colors",
      "Dimmable brightness",
      "Voice control compatible",
      "Scheduling and routines",
      "No hub required",
      "Energy efficient",
    ],
    specifications: {
      Wattage: "9W (60W equivalent)",
      Lumens: "800lm",
      "Color Temperature": "2700K-6500K",
      Connectivity: "Wi-Fi 2.4GHz",
      Compatibility: "Alexa, Google Assistant, HomeKit",
      Lifespan: "25,000 hours",
    },
    stock: 42,
    rating: 4.4,
    reviews: 156,
  },
  {
    id: "12",
    name: "Coffee Maker",
    price: 1799.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "home",
    description:
      "Start your day right with our programmable Coffee Maker. With customizable brewing options and a sleek design, it delivers perfect coffee every time and looks great in any kitchen.",
    features: [
      "12-cup capacity",
      "Programmable timer",
      "Multiple brew strengths",
      "Keep warm function",
      "Auto shut-off",
      "Removable water reservoir",
    ],
    specifications: {
      Capacity: "12 cups (60 oz)",
      Dimensions: "14 x 8 x 14 inches",
      Power: "1000W",
      "Water Reservoir": "Removable, 70 oz",
      "Filter Type": "Permanent gold-tone",
      Programs: "Regular, Bold, 1-4 cups",
    },
    stock: 18,
    rating: 4.6,
    reviews: 128,
  },
  {
    id: "13",
    name: "Air Purifier",
    price: 2999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "home",
    description:
      "Breathe cleaner, fresher air with our advanced Air Purifier. Using a multi-stage filtration system, it removes allergens, dust, and odors for improved air quality in your home or office.",
    features: [
      "HEPA filtration",
      "Activated carbon filter",
      "Air quality sensor",
      "Auto mode",
      "Sleep mode",
      "Filter replacement indicator",
    ],
    specifications: {
      "Coverage Area": "Up to 500 sq ft",
      "CADR Rating": "300 m³/h",
      "Noise Level": "24-54 dB",
      "Power Consumption": "40W",
      "Filter Life": "6-12 months",
      Dimensions: "21 x 12 x 12 inches",
    },
    stock: 14,
    rating: 4.7,
    reviews: 95,
  },
  {
    id: "14",
    name: "Robot Vacuum",
    price: 5999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "home",
    description:
      "Let our Robot Vacuum handle the cleaning while you focus on what matters. With smart navigation, powerful suction, and app control, it keeps your floors spotless with minimal effort.",
    features: [
      "Smart mapping technology",
      "2500Pa suction power",
      "150-minute runtime",
      "App and voice control",
      "Automatic recharging",
      "Scheduled cleaning",
    ],
    specifications: {
      "Suction Power": "2500Pa",
      Battery: "5200mAh",
      Runtime: "Up to 150 minutes",
      "Dust Bin Capacity": "600ml",
      "Noise Level": "<65 dB",
      "Climbing Ability": "Up to 2cm",
    },
    stock: 11,
    rating: 4.8,
    reviews: 173,
  },
  {
    id: "15",
    name: "Throw Blanket",
    price: 999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "home",
    description:
      "Add warmth and style to your home with our luxurious Throw Blanket. Made from premium materials, it's perfect for cozy nights on the couch or as an elegant accent for your bedroom.",
    features: [
      "Ultra-soft fabric",
      "Hypoallergenic",
      "Lightweight yet warm",
      "Elegant design",
      "Machine washable",
      "Multiple color options",
    ],
    specifications: {
      Material: "100% Organic Cotton",
      Dimensions: '50" x 60"',
      Weight: "3 lbs",
      Care: "Machine wash cold, tumble dry low",
      Origin: "Ethically made",
      Certifications: "OEKO-TEX Standard 100",
    },
    stock: 25,
    rating: 4.9,
    reviews: 87,
  },
  // Accessories
  {
    id: "16",
    name: "Phone Case",
    price: 399.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "accessories",
    description:
      "Protect your smartphone in style with our durable Phone Case. Designed for maximum protection without adding bulk, it features precise cutouts for easy access to all buttons and ports.",
    features: [
      "Military-grade drop protection",
      "Slim profile",
      "Wireless charging compatible",
      "Raised edges for screen protection",
      "Anti-yellowing material",
      "Tactile button covers",
    ],
    specifications: {
      Material: "Polycarbonate and TPU",
      Compatibility: "iPhone 13/14 series, Samsung Galaxy S22/S23 series",
      "Drop Protection": "Up to 10 feet",
      Thickness: "2.5mm",
      Weight: "35g",
      Warranty: "Lifetime",
    },
    stock: 48,
    rating: 4.6,
    reviews: 312,
  },
  {
    id: "17",
    name: "Wireless Charger",
    price: 699.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "accessories",
    description:
      "Charge your devices effortlessly with our Wireless Charger. Supporting fast charging for compatible devices, this sleek charger eliminates cable clutter and provides a convenient charging solution.",
    features: [
      "15W fast charging",
      "Multi-device compatibility",
      "LED charging indicator",
      "Anti-slip surface",
      "Foreign object detection",
      "Compact design",
    ],
    specifications: {
      Input: "QC 3.0 adapter (9V/2A)",
      Output: "15W max",
      "Charging Distance": "≤8mm",
      Dimensions: "100mm diameter",
      Compatibility: "Qi-enabled devices",
      "Cable Length": "1.5m",
    },
    stock: 29,
    rating: 4.5,
    reviews: 187,
  },
  {
    id: "18",
    name: "Laptop Sleeve",
    price: 499.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "accessories",
    description:
      "Keep your laptop protected with our stylish and functional Laptop Sleeve. The padded interior safeguards against bumps and scratches, while the water-resistant exterior provides protection from the elements.",
    features: [
      "Padded interior",
      "Water-resistant exterior",
      "Additional pocket for accessories",
      "Reinforced zipper",
      "Slim profile",
      "Carry handle",
    ],
    specifications: {
      Material: "Water-resistant polyester",
      Sizes: '13", 14", 15.6", 16"',
      "Interior Padding": "5mm foam",
      Weight: "280g",
      Colors: "Black, Navy, Gray",
      Warranty: "2 years",
    },
    stock: 36,
    rating: 4.7,
    reviews: 142,
  },
  {
    id: "19",
    name: "USB-C Hub",
    price: 999.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "accessories",
    description:
      "Expand your device's connectivity with our versatile USB-C Hub. Featuring multiple ports in a compact design, it's the perfect solution for connecting all your peripherals and accessories.",
    features: [
      "7-in-1 port expansion",
      "4K HDMI output",
      "SD and microSD card readers",
      "USB 3.0 ports",
      "100W Power Delivery",
      "Aluminum alloy construction",
    ],
    specifications: {
      Ports: "HDMI, 2x USB 3.0, SD, microSD, USB-C PD, Ethernet",
      "HDMI Output": "4K@30Hz",
      "Data Transfer": "Up to 5Gbps",
      "Power Delivery": "100W pass-through",
      Dimensions: "112 x 28 x 9mm",
      Compatibility: "MacBook, iPad Pro, Windows laptops, Android",
    },
    stock: 22,
    rating: 4.6,
    reviews: 156,
  },
  {
    id: "20",
    name: "Screen Protector",
    price: 299.99,
    image: "/placeholder.svg?height=600&width=600",
    category: "accessories",
    description:
      "Safeguard your device's screen with our premium Screen Protector. Offering superior scratch resistance and clarity, it preserves your display's pristine condition without affecting touch sensitivity.",
    features: [
      "9H hardness",
      "Oleophobic coating",
      "99% transparency",
      "Easy installation",
      "Case-friendly design",
      "Bubble-free application",
    ],
    specifications: {
      Material: "Tempered glass",
      Thickness: "0.33mm",
      Hardness: "9H",
      Compatibility: "Multiple smartphone and tablet models",
      "Package Includes": "2 screen protectors, cleaning kit, installation guide",
      Warranty: "Lifetime replacement",
    },
    stock: 54,
    rating: 4.4,
    reviews: 231,
  },
]

export type Product = (typeof productDatabase)[number]

export async function getProductById(id: string): Promise<Product | undefined> {
  return productDatabase.find((product) => product.id === id)
}

export function getAllProducts(): Product[] {
  return productDatabase
}

export function getProductsByCategory(category: string): Product[] {
  return productDatabase.filter((product) => product.category === category)
}

export function getTopSellingProducts(limit = 5): Product[] {
  // In a real app, this would be based on actual sales data
  // For now, we'll just sort by rating and take the top ones
  return [...productDatabase].sort((a, b) => b.rating - a.rating).slice(0, limit)
}
