import type { Product } from "./types"

export const featuredProducts: Product[] = [
  {
    id: "whey-protein-1",
    name: "Proteína Whey Premium",
    description: "Proteína de alta calidad para recuperación y crecimiento muscular",
    longDescription:
      "Nuestra Proteína Whey Premium proviene de vacas alimentadas con pasto y proporciona 24g de proteína por porción con mínimos carbohidratos y grasas. Es perfecta para la recuperación post-entrenamiento, ayudando a reconstruir el tejido muscular y apoyar tus objetivos de fitness. Disponible en múltiples sabores deliciosos.",
    price: 999.99,
    originalPrice: 1199.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    badge: "Más Vendido",
    rating: 4.8,
    features: [
      "24g de proteína por porción",
      "Baja en carbohidratos y grasas",
      "Se mezcla fácilmente",
      "Sin edulcorantes artificiales",
    ],
  },
  {
    id: "fat-burner-1",
    name: "Quemador de Grasa Termogénico",
    description: "Potente fórmula para acelerar el metabolismo y quemar grasa",
    price: 799.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Pérdida de Peso",
    rating: 4.6,
  },
  {
    id: "vitamin-pack-1",
    name: "Pack de Vitaminas Diarias",
    description: "Suplemento completo de vitaminas y minerales diarios",
    price: 599.99,
    originalPrice: 699.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Vitaminas",
    badge: "Nuevo",
    rating: 4.5,
  },
  {
    id: "protein-bar-pack-1",
    name: "Pack Variado de Barras Proteicas",
    description: "Surtido de sabores de barras altas en proteína y bajas en azúcar",
    price: 499.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Comida",
    badge: "Popular",
    rating: 4.3,
  },
  {
    id: "creatine-1",
    name: "Creatina Monohidrato Pura",
    description: "Aumenta la fuerza y la potencia durante los entrenamientos",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    rating: 4.9,
  },
  {
    id: "detox-tea-1",
    name: "Té Detox Adelgazante",
    description: "Infusión natural para desintoxicar y apoyar la pérdida de peso",
    price: 299.99,
    originalPrice: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Pérdida de Peso",
    rating: 4.4,
  },
  {
    id: "bcaa-1",
    name: "Fórmula de Recuperación BCAA",
    description: "Aminoácidos de cadena ramificada para recuperación muscular",
    price: 699.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    rating: 4.6,
  },
  {
    id: "meal-replacement-1",
    name: "Batido Sustitutivo de Comidas",
    description: "Batido nutritivo y bajo en calorías para control de peso",
    price: 499.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Pérdida de Peso",
    badge: "Efectivo",
    rating: 4.3,
  },
]

// All products for the products page
export const allProducts: Product[] = [
  ...featuredProducts,
  // Proteínas (6 total - 3 already in featured)
  {
    id: "whey-isolate-1",
    name: "Aislado de Proteína Whey",
    description: "Whey aislado ultra-filtrado con 27g de proteína por porción",
    price: 1099.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    rating: 4.7,
  },
  {
    id: "plant-protein-1",
    name: "Proteína Vegetal",
    description: "Proteína vegetal completa de fuentes de guisante, arroz y cáñamo",
    price: 899.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    badge: "Vegano",
    rating: 4.5,
  },
  {
    id: "casein-protein-1",
    name: "Proteína de Caseína Nocturna",
    description: "Liberación lenta de proteínas para nutrición durante la noche",
    price: 949.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    rating: 4.6,
  },

  // Vitaminas (5 total - 1 already in featured)
  {
    id: "omega3-1",
    name: "Aceite de Pescado Omega-3",
    description: "Aceite de pescado de alta potencia para la salud del corazón y el cerebro",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Vitaminas",
    rating: 4.8,
  },
  {
    id: "vitamin-d-1",
    name: "Vitamina D3 + K2",
    description: "Apoya la salud ósea y la función inmunológica",
    price: 319.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Vitaminas",
    rating: 4.9,
  },
  {
    id: "vitamin-b-complex",
    name: "Complejo de Vitamina B",
    description: "Fórmula completa de vitaminas B para energía y salud neurológica",
    price: 349.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Vitaminas",
    rating: 4.7,
  },
  {
    id: "multivitamin-1",
    name: "Multivitamínico Completo",
    description: "Fórmula completa con vitaminas y minerales esenciales",
    price: 449.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Vitaminas",
    badge: "Esencial",
    rating: 4.8,
  },

  // Comida (4 total - 1 already in featured)
  {
    id: "protein-pancake-1",
    name: "Mezcla para Panqueques Proteicos",
    description: "Deliciosa mezcla de alta proteína para panqueques y waffles",
    price: 259.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Comida",
    rating: 4.4,
  },
  {
    id: "protein-cookie-1",
    name: "Galletas Proteicas",
    description: "Galletas horneadas suaves con 15g de proteína cada una",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Comida",
    rating: 4.1,
  },
  {
    id: "protein-chips-1",
    name: "Chips Proteicas",
    description: "Snack crujiente alto en proteína y bajo en carbohidratos",
    price: 279.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Comida",
    badge: "Nuevo",
    rating: 4.2,
  },

  // Pérdida de Peso (6 total - 3 already in featured)
  {
    id: "cla-1",
    name: "CLA - Ácido Linoleico Conjugado",
    description: "Apoya la reducción de grasa corporal y mejora la composición corporal",
    price: 549.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Pérdida de Peso",
    rating: 4.3,
  },
  {
    id: "carb-blocker-1",
    name: "Bloqueador de Carbohidratos",
    description: "Ayuda a reducir la absorción de carbohidratos para control de peso",
    price: 479.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Pérdida de Peso",
    rating: 4.0,
  },
  {
    id: "appetite-suppressant-1",
    name: "Supresor del Apetito Natural",
    description: "Fórmula natural para controlar el hambre y reducir la ingesta calórica",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Pérdida de Peso",
    badge: "Efectivo",
    rating: 4.4,
  },

  // Additional products to reach 22 total
  {
    id: "collagen-1",
    name: "Péptidos de Colágeno",
    description: "Apoya la salud de la piel, cabello, uñas y articulaciones",
    price: 699.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Proteínas",
    rating: 4.7,
  },
  {
    id: "greens-powder-1",
    name: "Polvo de Superverdes",
    description: "Mezcla completa de vegetales ricos en nutrientes y antioxidantes",
    price: 599.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Vitaminas",
    badge: "Orgánico",
    rating: 4.3,
  },
]
